listaFrases = {"Ultimas notícias sobre a economia global.",
"Analise do cenario politico atual.",
"Como a tecnologia muda o mercado de trabalho.",
"Consequencias do aquecimento global.",
"Cobertura da eleicao presidencial.",
"Atualizacao sobre os conflitos internacionais.",
"Impacto da inteligencia artificial na sociedade.",
"Perspectivas para o mercado de criptomoedas.",
"Resumo das principais manchetes do dia.",
"O futuro da energia renovavel.",
"Entretenimento e cultura",
"Critica do novo filme."
"Resenha do album mais recente.",
"Melhores series de ficcao cientifica.",
"Guia de festivais de musica.",
"Lancamentos de jogos eletronicos.",
"Entrevista com um autor famoso.",
"Historias por tras dos bastidores de Hollywood.",
"Analise de tendencias de moda.",
"Documentarios premiados.",
"Obras de arte mais influentes da historia.",
"Saude e bem-estar",
"Dicas para melhorar a qualidade do sono.",
"Beneficios da meditacao para a mente.",
"Rotina de exercicios para iniciantes.",
"Receitas saudaveis para o jantar.",
"Mitos e verdades sobre suplementos.",
"Como combater o estresse.",
"Alimentos que fortalecem a imunidade.",
"Guia completo para uma vida saudavel.",
"Importancia da hidratacao diaria.",
"Tecnicas de respiracao para relaxar.",
"Viagem e lazer",
"Melhores destinos para viajar em familia.",
"Guia de viagem para a Asia.",
"Roteiro de mochilao na America do Sul.",
"Cidades mais seguras para turistas.",
"Como planejar uma viagem de baixo custo.",
"Dicas para viajar com animais de estimacao.",
"Experiencias de intercambio.",
"Praias paradisacas no Brasil.",
"Melhores parques tematicos do mundo.",
"Curiosidades sobre monumentos historicos.",
"Tecnologia e gadgets",
"Analise do novo smartphone da Apple.",
"O que esperar da proxima geracao de consoles.",
"Guia de compra de notebooks.",
"Melhores aplicativos para produtividade.",
"Seguranca digital para o dia a dia.",
"Como montar um computador para jogos.",
"Resenha de fones de ouvido sem fio.",
"Inovacoes em carros eletricos.",
"Tendencias em realidade virtual.",
"Futuro da inteligencia artificial.",
"Financas e investimentos",
"Como comecar a investir em acoes.",
"Guia para iniciantes em financas pessoais.",
"Oportunidades no mercado imobiliario.",
"Dicas para economizar dinheiro.",
"Melhores investimentos a longo prazo.",
"Entendendo os fundos de investimento.",
"Como construir uma reserva de emergencia.",
"Tendencias de fintechs.",
"Estrategias para quitar dividas.",
"O guia completo sobre aposentadoria.",
"Culinária e gastronomia",
"Receitas de sobremesas faceis.",
"Guia de vinhos para iniciantes.",
"Melhores restaurantes em Sao Paulo.",
"Como fazer pao caseiro.",
"Historias da gastronomia mundial.",
"Receitas veganas criativas.",
"Segredos de chefs renomados.",
"Como harmonizar vinho e comida.",
"Culinaria japonesa tradicional.",
"Os temperos essenciais da cozinha.",
"Ciencia e educacao",
"Descobertas cientificas mais recentes.",
"O universo e suas galaxias.",
"A importancia da educacao continuada.",
"Como aprender um novo idioma.",
"Curiosidades sobre o corpo humano.",
"A historia da matematica.",
"O futuro da pesquisa espacial.",
"A evolucao das especies.",
"O que sao buracos negros.",
"Biografias de cientistas famosos.",
"Esportes",
"Resumo dos jogos de futebol da semana.",
"Analise do desempenho de um time.",
"Entrevistas com atletas.",
"Como a tecnologia impacta o esporte.",
"Treinamento para maratonas.",
"A historia dos Jogos Olimpicos.",
"Melhores momentos da temporada.",
"Estrategias de jogo no basquete.",
"Curiosidades sobre a Formula 1.",
"Ranking dos melhores tenistas.",
"Diversos e aleatorios",
"Como consertar pequenos problemas em casa.",
"Dicas para organizar o guarda-roupa.",
"A historia da fotografia.",
"Guia de jardinagem para iniciantes.",
"Curiosidades sobre animais selvagens.",
"O que e minimalismo.",
"Como pintar paredes em casa.",
"Melhores hobbies para o tempo livre.",
"A evolucao da arquitetura.",
"Como fazer um podcast.",
"Impacto da inteligência artificial na educação básica.",
"Receitas veganas de sobremesas com chocolate.",
"Como planejar uma viagem de baixo custo para a Europa.",
"Guia completo para começar a investir na bolsa de valores.",
"Melhores praticas de seguranca cibernetica para empresas pequenas.",
"Novos estudos sobre a relacao entre sono e memoria.",
"Criticas sobre o filme vencedor do Festival de Cannes.",
"Historia da arquitetura moderna no Brasil.",
"Exercicios de meditacao para iniciantes.",
"Beneficios do consumo de frutas vermelhas para a saude.",
"O futuro dos carros eletricos na industria automotiva.",
"Tendencias de moda sustentavel para o proximo ano.",
"Como escrever um roteiro de podcast de sucesso.",
"As melhores praias do Nordeste para viajar em familia.",
"Analise do mercado de criptomoedas nos ultimos 6 meses.",
"Entrevista com um renomado chef de cozinha internacional.",
"Guia de jardinagem para cultivar temperos em apartamento.",
"Curiosidades sobre a vida animal nas florestas tropicais.",
"Dicas para melhorar a produtividade no trabalho remoto.",
"Os maiores avancos cientificos da ultima decada.",
"Entrevista com um dos maiores empresarios de tecnologia.",
"A evolucao dos videogames desde os anos 80.",
"Como a pandemia mudou o comportamento do consumidor.",
"Melhores aplicativos para aprender um novo idioma.",
"Resenha do novo livro de ficção de um autor famoso.",
"Roteiro de viagem para quem ama historia em Roma.",
"A importancia da empatia nas relacoes interpessoais.",
"Passo a passo para fazer pao de fermentacao natural.",
"O impacto das redes sociais na saude mental dos jovens.",
"Tendencias de design de interiores para 2026.",
"Guia de exercicios para fortalecer a regiao lombar.",
"Desafios e oportunidades do mercado de trabalho para autonomos.",
"Como comecar um pequeno negocio online.",
"Analise das principais manchetes da semana.",
"Melhores documentarios sobre historia e cultura.",
"Beneficios de ter um animal de estimacao em casa.",
"A biografia de um grande lider politico.",
"Curiosidades sobre os misterios do espaco sideral.",
"Como a tecnologia esta moldando o futuro da medicina.",
"Onde encontrar os melhores restaurantes de comida tailandesa.",
"Dicas para economizar dinheiro e organizar as financas.",
"Os impactos das mudanças climaticas no meio ambiente.",
"A historia dos grandes movimentos sociais do seculo XX.",
"Resumo dos jogos de futebol do campeonato nacional.",
"Como praticar a gratidao no dia a dia.",
"As melhores series de suspense da atualidade.",
"Guia de compra de cameras fotograficas para iniciantes.",
"Analise do mercado imobiliario em grandes cidades.",
"O papel da sustentabilidade na industria da moda.",
"Tendencias de marketing digital para pequenas empresas.",
"Como lidar com o estresse e a ansiedade.",
"Analise de mercado de imoveis para investimento.",
"O que esperar da nova geracao de consoles de videogame.",
"Melhores destinos para viajar sozinho.",
"Beneficios de uma alimentacao rica em fibras.",
"A influencia da musica na cultura popular.",
"Como a inteligencia artificial esta transformando a arte.",
"Passo a passo para aprender a tocar violao.",
"Guia de vinhos para harmonizar com massas.",
"O impacto do trabalho voluntario na comunidade.",
"Curiosidades sobre a mitologia grega e romana.",
"Como a tecnologia está afetando o mercado de trabalho.",
"Dicas para otimizar o uso de redes sociais.",
"Analise do comportamento dos consumidores online.",
"Beneficios do exercicio fisico para a saude mental.",
"Tendencias de inovacao na industria de tecnologia.",
"As melhores plataformas para aprender cursos online.",
"Resenha de um livro classico da literatura brasileira.",
"O futuro da educacao a distancia.",
"Como a inteligencia artificial pode melhorar o dia a dia.",
"Dicas para escolher um novo hobby.",
"Guia de como começar a correr.",
"Beneficios de uma rotina matinal produtiva.",
"Analise dos principais eventos esportivos.",
"Como a meditacao pode ajudar a lidar com a pressao.",
"Tendencias de mercado para a proxima decada.",
"Os maiores desafios da sustentabilidade ambiental.",
"Como a tecnologia esta revolucionando a industria da musica.",
"Onde encontrar os melhores museus de arte do mundo.",
"Como a tecnologia esta mudando a forma como interagimos.",
"Guia para investir em fundos imobiliarios.",
"Receitas saudaveis para o cafe da manha.",
"A importancia da diversidade e inclusao nas empresas.",
"Como a inteligencia artificial esta sendo usada na agricultura.",
"Melhores destinos para viajar com pouco dinheiro.",
"Beneficios de ter uma rotina de exercicios fisicos.",
"Analise dos principais problemas sociais do mundo.",
"Como a inteligencia artificial pode ser usada na area da saude.",
"Tendencias de decoracao para ambientes pequenos.",
"Os maiores avancos da ciencia nos ultimos anos.",
"A historia dos grandes navegadores.",
"Dicas para lidar com o burnout no trabalho.",
"Beneficios do consumo de agua para a saude.",
"Como a tecnologia esta mudando a forma como aprendemos.",
"Guia de como montar um home office eficiente.",
"Guia de como planejar um casamento sustentável.",
"Analise dos principais eventos culturais do ano.",
"Tendencias de empreendedorismo para jovens.",
"Os maiores avancos da engenharia moderna.",
"Dicas para melhorar a qualidade do sono.",
"Beneficios de praticar esportes ao ar livre.",
"O futuro do transporte publico.",
"Melhores destinos para viajar com crianças pequenas.",
"Novas descobertas sobre a vida em Marte.",
"Impacto da agricultura organica na biodiversidade.",
"Como a nanotecnologia pode revolucionar a medicina.",
"Melhores praticas para seguranca de dados em nuvem.",
"A influencia da arquitetura romana na Europa.",
"Como a inteligencia artificial esta sendo usada na educacao.",
"Receitas de drinques sem alcool para festas.",
"Guia de exercicios de alta intensidade para queimar calorias.",
"Tendencias de design grafico para 2026.",
"A historia dos grandes navegadores portugueses.",
"Analise do mercado de carros eletricos na China.",
"Beneficios da pratica regular de yoga.",
"Como construir uma rotina de autocuidado.",
"Beneficios da leitura para o desenvolvimento cognitivo.",
"O futuro da inteligencia artificial na automacao industrial.",
"Melhores museus de historia natural do mundo.",
"Como a musica afeta o humor e o bem-estar.",
"Passo a passo para fazer velas artesanais em casa.",
"Guia de viagem para a Islandia no inverno.",
"Curiosidades sobre a vida marinha no oceano profundo.",
"A biografia de um grande lider da historia.",
"Tendencias de maquiagem para o verao.",
"Analise do desempenho de um time de basquete.",
"Entrevista com um atleta olimpico.",
"Dicas para aprimorar as habilidades de comunicacao.",
"A importancia da empatia no ambiente de trabalho.",
"Como fazer um plano de negocios para startups.",
"Melhores podcasts sobre financas pessoais.",
"Beneficios do exercicio fisico para a saude mental.",
"Analise dos principais problemas sociais do mundo.",
"A historia dos grandes movimentos sociais do seculo XX.",
"Resumo dos jogos de futebol da semana.",
"Como praticar a gratidao no dia a dia.",
"As melhores series de suspense da atualidade.",
"Guia de compra de cameras fotograficas para iniciantes.",
"O papel da sustentabilidade na industria da moda.",
"Tendencias de marketing digital para pequenas empresas.",
"Como lidar com o estresse e a ansiedade.",
"Analise de mercado de imoveis para investimento.",
"Melhores destinos para viajar sozinho.",
"Beneficios de uma alimentacao rica em fibras.",
"A influencia da musica na cultura popular.",
"Como a inteligencia artificial esta transformando a arte.",
"Passo a passo para aprender a tocar violao.",
"Criticas sobre os principais lancamentos do cinema.",
"Guia de vinhos para harmonizar com massas.",
"O impacto do trabalho voluntario na comunidade.",
"Curiosidades sobre a mitologia grega e romana.",
"Como a tecnologia esta afetando o mercado de trabalho.",
"Dicas para otimizar o uso de redes sociais.",
"Analise do comportamento dos consumidores online.",
"Beneficios do exercicio fisico para a saude mental.",
"Tendencias de inovacao na industria de tecnologia.",
"As melhores plataformas para aprender cursos online.",
"O futuro da educacao a distancia.",
"Como a inteligencia artificial pode melhorar o dia a dia.",
"Dicas para escolher um novo hobby.",
"Guia de como começar a correr.",
"Beneficios de uma rotina matinal produtiva.",
"Analise dos principais eventos esportivos.",
"Como a meditacao pode ajudar a lidar com a pressao.",
"Tendencias de mercado para a proxima decada.",
"Os maiores desafios da sustentabilidade ambiental.",
"Onde encontrar os melhores museus de arte do mundo.",
"Como a tecnologia esta mudando a forma como interagimos.",
"Guia para investir em fundos imobiliarios.",
"Receitas saudaveis para o cafe da manha.",
"A importancia da diversidade e inclusao nas empresas.",
"Melhores destinos para viajar com pouco dinheiro.",
"Beneficios de ter uma rotina de exercicios fisicos.",
"Analise dos principais problemas ambientais.",
"Melhores destinos para viajar com criancas pequenas.",
"Como a inteligencia artificial pode ser usada na area da saude.",
"Tendencias de decoracao para ambientes pequenos.",
"A historia dos grandes navegadores.",
"Dicas para lidar com o burnout no trabalho.",
"Beneficios do consumo de agua para a saude.",
"Como a tecnologia esta mudando a forma como aprendemos.",
"As melhores series de ficcao cientifica.",
"Guia de como planejar um casamento sustentável.",
"Analise dos principais eventos culturais do ano.",
"Tendencias de empreendedorismo para jovens.",
"Os maiores avanços da engenharia moderna.",
"Dicas para melhorar a qualidade do sono.",
"Beneficios do consumo de frutas vermelhas para a saude.",
"Tutorial para montar um computador gamer.",
"O futuro dos carros eletricos na industria automotiva.",
"Analise dos resultados das eleicoes nos Estados Unidos.",
"Exercicios de meditacao para iniciantes.",
"Historia da arquitetura moderna no Brasil.",
"Criticas sobre o filme vencedor do Festival de Cannes.",
"Novos estudos sobre a relacao entre sono e memoria.",
"Melhores praticas de seguranca cibernetica para empresas pequenas.",
"Como a pandemia mudou o comportamento do consumidor.",
"Melhores aplicativos para aprender um novo idioma.",
"Resenha do novo livro de ficcao de um autor famoso.",
"Roteiro de viagem para quem ama historia em Roma.",
"Passo a passo para fazer pao de fermentacao natural.",
"O impacto das redes sociais na saude mental dos jovens.",
"Tendencias de design de interiores para 2026.",
"Desafios e oportunidades do mercado de trabalho para autonomos.",
"Como comecar um pequeno negocio online."
}